import '@/styles/global.scss'
import type { Metadata } from 'next'

import Hmbgr from "@/components/hmbgr";
import Heading from "@/components/heading";
import Profile from "@/components/profile";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <nav id="mainNav">
          <Hmbgr/>
          <Heading/>
          <Profile/>
        </nav>
      </body>
    </html>
  )
}
